### ISSUE TITLE
content missing

### ISSUE THREAD

**Issue by eikaramba** [frontarm/async-javascript-cheatsheet#2]
is it really everyhting? i don't have pro but could imagine the contents of Sequential vs. Parallel are missing. i guess they describe e.g. to use reduce() in order to make an array of promises be executed sequential before finally doing something else.

**Comment by jamesknelson** [comment]
Yeah, this is just as much as I could fit on a cheatsheet. The course itself goes into depth with many more examples and exercises.

For example, the Sequential vs. Parallel lesson contains an exercise that shows how the order in which you `await` can change the total amount of time that a function takes to execute. But I couldn't figure out how to fit that on the cheatsheet so I just left it out.

Going to close this for now. But let me know if you have any suggestions for specific changes!
